export const MAX_NUMBER_LIMIT = 9999999999999.99;
export const MIN_NUMBER_LIMIT = -9999999999999.99;
export const PROGRESS_TOTAL_STEPS = 3;

export const CURRENCY_OPTIONS = [
    { value: "AED", label: "AED - United Arab Emirates Dirham" },
    { value: "ARS", label: "ARS - Argentine Peso" },
    { value: "AUD", label: "AUD - Australian Dollar" },
    { value: "BGN", label: "BGN - Bulgarian Lev" },
    { value: "BRL", label: "BRL - Brazilian Real" },
    { value: "CAD", label: "CAD - Canadian Dollar" },
    { value: "CHF", label: "CHF - Swiss Franc" },
    { value: "CLP", label: "CLP - Chilean Peso" },
    { value: "CNY", label: "CNY - Chinese Yuan" },
    { value: "COP", label: "COP - Colombian Peso" },
    { value: "CZK", label: "CZK - Czech Koruna" },
    { value: "DKK", label: "DKK - Danish Krone" },
    { value: "EGP", label: "EGP - Egyptian Pound" },
    { value: "EUR", label: "EUR - Euro" },
    { value: "GBP", label: "GBP - British Pound" },
    { value: "HKD", label: "HKD - Hong Kong Dollar" },
    { value: "HUF", label: "HUF - Hungarian Forint" },
    { value: "IDR", label: "IDR - Indonesian Rupiah" },
    { value: "ILS", label: "ILS - Israeli New Shekel" },
    { value: "INR", label: "INR - Indian Rupee" },
    { value: "JPY", label: "JPY - Japanese Yen" },
    { value: "KZT", label: "KZT - Kazakhstani Tenge" },
    { value: "KRW", label: "KRW - South Korean Won" },
    { value: "MXN", label: "MXN - Mexican Peso" },
    { value: "MYR", label: "MYR - Malaysian Ringgit" },
    { value: "NGN", label: "NGN - Nigerian Naira" },
    { value: "NOK", label: "NOK - Norwegian Krone" },
    { value: "NZD", label: "NZD - New Zealand Dollar" },
    { value: "PKR", label: "PKR - Pakistani Rupee" },
    { value: "PLN", label: "PLN - Polish Zloty" },
    { value: "RON", label: "RON - Romanian Leu" },
    { value: "SAR", label: "SAR - Saudi Riyal" },
    { value: "SEK", label: "SEK - Swedish Krona" },
    { value: "SGD", label: "SGD - Singapore Dollar" },
    { value: "THB", label: "THB - Thai Baht" },
    { value: "TRY", label: "TRY - Turkish Lira" },
    { value: "UAH", label: "UAH - Ukrainian Hryvnia" },
    { value: "USD", label: "USD - US Dollar" },
    { value: "ZAR", label: "ZAR - South African Rand" },
];
